//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanNet.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AttendanceBridges = new HashSet<AttendanceBridge>();
            this.Mistakes = new HashSet<Mistake>();
            this.Posts = new HashSet<Post>();
            this.TrucCongs = new HashSet<TrucCong>();
        }
    
        public int IDAccount { get; set; }
        public string Password { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> Order { get; set; }
        public string Meta { get; set; }
        public System.DateTime DateBegin { get; set; }
        public int Hide { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string MSSV { get; set; }
        public Nullable<int> IDSinhVien { get; set; }
        public Nullable<int> IDTeacher { get; set; }
    
        
        public virtual AccountType AccountType { get; set; }
        [JsonIgnore]
        public virtual SinhVien SinhVien { get; set; }
        [JsonIgnore]
        
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<AttendanceBridge> AttendanceBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Mistake> Mistakes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Post> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<TrucCong> TrucCongs { get; set; }
    }
}
