//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanNet.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int IDContract { get; set; }
        public string IDCitizen { get; set; }
        public Nullable<int> ProfilePlace { get; set; }
        public string IDPlace { get; set; }
        public Nullable<int> Order { get; set; }
        public string Meta { get; set; }
        public System.DateTime DateBegin { get; set; }
        public int Hide { get; set; }
        public Nullable<int> IDPriority { get; set; }
        public string Description { get; set; }
        public Nullable<bool> xetduyet { get; set; }
        public Nullable<System.DateTime> TimeExpired { get; set; }
        public Nullable<int> IDSinhVien { get; set; }

        [JsonIgnore]
        public virtual Place Place { get; set; }
        [JsonIgnore]
        public virtual SinhVien SinhVien { get; set; }
        [JsonIgnore]
        public virtual Priority Priority { get; set; }
    }
}
